export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const NEW_TASK_START = "NEW_TASK_START";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";
export const NEW_TASK_FAIL = "NEW_TASK_FAIL";

export const GET_TASKS_START = "GET TASK_START";
export const GET_TASKS_SUCCESS = "GET TASK_SUCCESS";
export const GET_TASKS_FAIL = "GET TASK_FAIL";
